baseurl = "/"
languageCode = "en-us"
title = "Homepage"

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]
  [mediaTypes."text/html"]
    suffixes = ["html"]

# Redefine HTML to update its media type.
#[outputFormats]
#  [outputFormats.HTML]
#    mediaType = "text/html"

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS", "JSON"]
  taxonomy = ["HTML", "RSS", "JSON"]
  taxonomyTerm = ["HTML", "RSS", "JSON"]
